### PR TITLE
Change module names and change naming to reflect change from model to model manager

### PR DESCRIPTION
**Pull request by alicerdv**
## What is the goal of this PR?

This PR changes the naming of some modules and makes the naming more consistent with the use of ModelManager

## What are the changes implemented in this PR?

Changed names of modules (data -> data_managers, models-> model_managers)
Changed names of classes in model_managers to include ModelManager in the name, instead of just Model
Changed names of input arguments from model to model_manager. ie the input to the strategy and the input to the pipeline

### CODE REVIEW

**Comment by alicerdv** [comment]
I've realised that there are some changes to the notebooks that need to be made to reflect these changes, I will make those changes after Alison's PR has been merged

**Comment by paulmorio** [comment]
Thank you for this, will review in detail when the update is done.

**Review by thomasgaudelet — APPROVED** [review]

**Review by a-pouplin — APPROVED** [review]
LGTM :)

**Review by thomasgaudelet — APPROVED** [review]

**Review by paulmorio — APPROVED** [review]
LGTM!

**Pull request merged**
